"""
Per-faction sidebars. Red Alert's sidebar sheet (ra|uibits/sidebar.png) carries one 222x222 emblem panel per
side (Allied eagle, Soviet hammer and sickle) where the radar would be. For each Napoleonic faction this writes
a copy of that sheet with the faction's Blender flag panel (art/renders/sidebar/<faction>.png, from
art/blender/scripts/nw_sidebar.py) in the radar slot, the chrome collections for it, and the faction suffix.

Usage: python art/tools/make_sidebars.py
"""
import os
from PIL import Image

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
MOD = os.path.join(ROOT, "mods", "napoleonic")
RENDERS = os.path.join(ROOT, "art", "renders", "sidebar")
FACTIONS = ["france", "england", "russia", "prussia", "austria"]
RADAR = (290, 67, 222, 222)

# Every chrome collection the sidebar looks up with the faction suffix (as defined for "allies" in ra|chrome.yaml).
SUFFIXED = ["sidebar-button-{}", "sidebar-button-{}-hover", "sidebar-button-{}-pressed", "sidebar-button-{}-highlighted",
            "sidebar-button-{}-highlighted-hover", "sidebar-button-{}-highlighted-pressed", "sidebar-button-{}-disabled",
            "sidebar-button-{}-highlighted-disabled", "command-button-{}", "command-button-{}-hover",
            "command-button-{}-pressed", "command-button-{}-highlighted", "command-button-{}-highlighted-hover",
            "command-button-{}-highlighted-pressed", "command-button-{}-disabled", "command-button-{}-highlighted-disabled"]


def main():
    base = Image.open(os.path.join(ROOT, "mods", "ra", "uibits", "sidebar.png")).convert("RGBA")
    chrome = ["# GENERATED by art/tools/make_sidebars.py: per-faction sidebars with the nation's flag in the radar panel.",
              "# Buttons and frame reuse Red Alert's Allied sidebar artwork.", ""]
    for f in FACTIONS:
        panel = Image.open(os.path.join(RENDERS, f + ".png")).convert("RGBA").resize(RADAR[2:], Image.LANCZOS)
        sheet = base.copy()
        sheet.paste(panel, RADAR[:2])
        sheet.save(os.path.join(MOD, "uibits", f"sidebar-{f}.png"))
        chrome += [f"sidebar-{f}:", f"\tImage: sidebar-{f}.png", "\tRegions:",
                   f"\t\tradar: {', '.join(map(str, RADAR))}",
                   "\t\tbackground-top: 0, 185, 238, 262", "\t\tbackground-moneybin: 0, 85, 238, 28",
                   "\t\tbackground-iconbg: 12, 227, 190, 47", "\t\tbackground-iconrow: 0, 116, 238, 47",
                   "\t\tbackground-bottom: 0, 166, 238, 8", "\t\tbackground-supportoverlay: 12, 324, 64, 48", ""]
        for name in SUFFIXED:
            chrome += [name.format(f) + ":", "\tInherits: " + name.format("allies")]
        chrome.append("")
    with open(os.path.join(MOD, "chrome-sidebars.yaml"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(chrome).rstrip("\n") + "\n")
    with open(os.path.join(MOD, "metrics.yaml"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("Metrics:\n" + "".join(f"\tFactionSuffix-{f}: {f}\n" for f in FACTIONS))
    print("sidebars:", ", ".join(FACTIONS))


if __name__ == "__main__":
    main()
